export const WELCOME_ACTIONS = {
	UPDATE_MEETING_ROOMS: 'UPDATE_MEETING_ROOMS',
	UPDATE_HOST: 'UPDATE_HOST',
	TOGGLE_LOADING: 'TOGGLE_LOADING'
}

export const PROFILE_ACTIONS = {
	TOGGLE_MODAL: 'TOGGLE_MODAL',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	FALSE_PROFILE_FLAG: 'FALSE_PROFILE_FLAG',
	TRUE_PROFILE_FLAG: 'TRUE_PROFILE_FLAG',
	UPDATE_PHOTOS: 'UPDATE_PHOTOS',
	SELECT_PHOTO: 'SELECT_PHOTO'
}

export const ROOM_ACTIONS = {
	UPDATE_ROOM_ID: 'UPDATE_ROOM_ID',
	UPDATE_TOKEN: 'UPDATE_TOKEN'
}