export const WELCOME_ACTIONS = {
	UPDATE_UUIDS: 'UPDATE_UUIDS',
	UPDATE_BEACONS: 'UPDATE_BEACONS',
	UPDATE_HOST: 'UPDATE_HOST',
}

export const PROFILE_ACTIONS = {
	TOGGLE_MODAL: 'TOGGLE_MODAL',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	FALSE_PROFILE_FLAG: 'FALSE_PROFILE_FLAG',
	TRUE_PROFILE_FLAG: 'TRUE_PROFILE_FLAG',
	UPDATE_PHOTOS: 'UPDATE_PHOTOS',
	SELECT_PHOTO: 'SELECT_PHOTO'
}
